#!/bin/csh

java SortPerf select 5 50 1000 select.dat
java SortPerf insert 5 50 1000 insert.dat
java SortPerf merge 5 50 1000 merge.dat
java SortPerf quick 5 50 1000 quick.dat
java SortPerf best 5 50 1000 best.dat
